import type { Metadata } from 'next'
import { Archivo } from 'next/font/google'
import './globals.css'
import NextAuthSessionProvider from '@/provider/NextAuthSessionProvider'
import ToastProvider from '@/provider/ToastProvider'

const inter = Archivo({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">    
      <body className={`${inter.className} h-[100vh] overflow-x-hidden w-[100vw]`}>
        <ToastProvider />
        <NextAuthSessionProvider>
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
